### ISSUE TITLE
Updates for self-hosted runner

### ISSUE THREAD

**Issue by cboettig** [eco4cast/usgsrc4cast-ci#100]
@jzwart I've needed to juggle things for the self-hosted runner to better accommodate loads.  

For any tasks that need a self-hosted runner, you will need to request the `efi-cirrus` runner group as in this [example](https://github.com/eco4cast/neon4cast-ci/blob/main/.github/workflows/self_hosted_test.yml), like so:

```
    runs-on: efi-cirrus
    container: 
      # IMPORTANT.  Please set a memory limit <= 45 GB.
      image: eco4cast/rocker-neon4cast:latest
      options: --memory="15g"
    steps:
```

It's really important you include the `options: memory="15g"` (or whatever up to 45 g) in any workflows on the self-hosted runner.  (Unfortunately/astonishingly, GitHub ARC doesn't provide a mechanism to enforce this on runners that use custom docker images other than opting in to limits in the job yaml).
